---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
                - 5000:5000 
        image: amymanning1/iss_tracker:midterm
